<a href="https://colab.research.google.com/github/aryansingh12/tensorflow-keras/blob/master/keras_autoencoder.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from keras.layers import Input, Dense, Conv2D, MaxPooling2D, UpSampling2D
from keras.models import Model
from keras.datasets import mnist
import numpy as np
import matplotlib.pyplot as plt
from keras import regularizers
from keras.layers import LSTM, RepeatVector
from keras import backend as K
from keras.callbacks import TensorBoard

In [7]:
encoding_dim = 32

input_img = Input(shape=(784,))# change this to the vector size

encoded = Dense(encoding_dim, activation='relu')(input_img)

decoded = Dense(784, activation='sigmoid')(encoded)

autoencoder = Model(input_img, decoded)

In [0]:
encoder = Model(input_img, encoded)

In [0]:
encoded_input = Input(shape=(encoding_dim,))

decoder_layer = autoencoder.layers[-1]

decoder = Model(encoded_input, decoder_layer(encoded_input))

In [10]:
autoencoder.compile(optimizer='adadelta', loss='binary_crossentropy')



Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [12]:
(x_train, _), (x_test, _) = mnist.load_data()
print(x_train, x_test)

[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]] [[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ...

In [14]:
x_train = x_train.astype('float32') / 255.
x_test = x_test.astype('float32') / 255.
x_train = x_train.reshape((len(x_train), np.prod(x_train.shape[1:])))
x_test = x_test.reshape((len(x_test), np.prod(x_test.shape[1:])))
print(x_train.shape)
print(x_test.shape)

(60000, 784)
(10000, 784)


In [15]:
autoencoder.fit(x_train, x_train, 
               epochs=50,
               batch_size=256,
               shuffle=True,
               validation_data=(x_test, x_test))




Train on 60000 samples, validate on 10000 samples
Epoch 1/50





60000/60000 [==============================] - 4s 68us/step - loss: 0.3680 - val_loss: 0.2713
Epoch 2/50
60000/60000 [==============================] - 3s 58us/step - loss: 0.2639 - val_loss: 0.2533
Epoch 3/50
60000/60000 [==============================] - 3s 58us/step - loss: 0.2431 - val_loss: 0.2308
Epoch 4/50
60000/60000 [==============================] - 3s 57us/step - loss: 0.2229 - val_loss: 0.2131
Epoch 5/50
60000/60000 [==============================] - 3s 56us/step - loss: 0.2080 - val_loss: 0.2007
Epoch 6/50
60000/60000 [==============================] - 3s 57us/step - loss: 0.1969 - val_loss: 0.1909
Epoch 7/50
60000/60000 [==============================] - 3s 58us/step - loss: 0.1883 - val_loss: 0.1832
Epoch 8/50
60000/60000 [==============================] - 3s 56us/step - loss: 0.1813 - val_loss: 0.1768
Epoch 9/50
60000/60000 [==============================] - 3s 56us/step - loss: 0.1753 - val_loss: 0.17

In [0]:
# encode and decode some digits
# note that we take them from the *test* set
encoded_imgs = encoder.predict(x_test)
decoded_imgs = decoder.predict(encoded_imgs)

In [18]:
print(encoded_imgs)
print(decoded_imgs)

[[ 1.393893    4.819203    9.537659   ...  6.256948   13.205536
   0.264432  ]
 [ 0.71996534  4.2163396   2.2182193  ...  2.8982372   8.039322
  10.635311  ]
 [ 0.          1.6059046   0.55333424 ...  3.0830688   8.8151245
   5.595712  ]
 ...
 [ 3.2905495   4.194705   10.016529   ...  4.410598    9.369423
   7.832072  ]
 [ 4.7598643   0.          8.589058   ...  9.324636    4.3521852
   6.5861654 ]
 [ 6.5719805   9.447805    2.5079696  ... 11.034837    1.5451813
  15.647144  ]]
[[2.7120113e-05 4.5508146e-05 3.6209822e-05 ... 1.7225742e-05
  1.1503696e-05 6.3478947e-06]
 [8.1032515e-05 2.5451183e-05 1.7583370e-06 ... 7.5459480e-05
  8.1360340e-06 2.4735928e-06]
 [2.9939413e-04 9.6946955e-05 1.1691451e-04 ... 2.5188923e-04
  1.0883808e-04 1.4114380e-04]
 ...
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00
  5.9604645e-08 0.0000000e+00]
 [6.0796738e-06 1.7583370e-06 9.2387199e-07 ... 1.0579824e-05
  3.7848949e-06 5.6624413e-07]
 [0.0000000e+00 0.0000000e+00 0.0000000e+00 ...